############################################################
# nixpacks.toml  –  lean Flask + Torch API
# • Uses Python 3.11  (pre‑built wheels exist)
# • Installs no build tool‑chain → keeps image <4 GB
# • Runs the app with Gunicorn
############################################################

############################
# 1.  Base runtime packages
############################
[phases.setup]
# Only Python and a minimal libc; no dev headers
nixPkgs = ["python311"]

############################
# 2.  Python dependencies
############################
[phases.install]
#  --no-cache-dir avoids pip cache bloat; final rm for good measure
cmds = [
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt",
  "rm -rf ~/.cache/pip"
]

############################
# 3.  Start your Flask app
############################
[processes]
web = "gunicorn app:app --bind 0.0.0.0:${PORT:-8000}"
