# nixpacks.toml
[variables]
BP_PYTHON_VERSION = "3.11.9"

[pkg]
apt = [
  "build-essential",
  "zlib1g-dev",
  "libjpeg-dev",
  "libpng-dev",
  "libtiff-dev",
  "libwebp-dev",
  "libfreetype6-dev"
]

[processes]
web = "gunicorn app:app --bind 0.0.0.0:${PORT:-8000}"
